### ISSUE TITLE
存储信息被删得太狠，还是直接用推文 json 来存储好啦

### ISSUE THREAD

**Issue by shellexy** [ahxxm/timeline-storage#1]
比如该推文的上下文对话串，发推当时的描述、背景图，以及其他的信息都被 AI 乃删掉了，
还是直接用 json 保留完整信息好啦

**Comment by shellexy** [comment]
那些信息就算现在不处理，也完整保存下来以供日后打算呀

**Comment by ahxxm** [comment]
我试着这么存了一下，一两天就几百M了，还没研究怎么压缩...

**Comment by ahxxm** [comment]
哎对，试过默认的wired tiger，单核cpu压力比较大

**Comment by shellexy** [comment]
直接当成字符串存储进去好啦。
我自己是把推文 json（先用 json.dumps(obj, ensure_ascii=0, indent=0) 干掉 unicode 转义）用 bsddb btree 来存储的，mongodb 可能每个键值的额外开销比较大，用字符串代替应该就能省了。

**Comment by shellexy** [comment]
不过，WiredTiger 默认的 Snappy 应该不至于单核 cpu 跑满吧

**Comment by ahxxm** [comment]
你这样咋搜索...

**Comment by shellexy** [comment]
遍历或者自己索引呀，
AI 酱的话在原先的代码里多存储一个 jsonstr 键值好了

**Comment by ahxxm** [comment]
我准备试试[postgres的toast](http://www.postgresql.org/docs/9.5/static/storage-toast.html)....

**Comment by shellexy** [comment]
postgresql 本身就支持 json 和 jsonb 字段类型呀，
sqlite 3.9 也支持 json 不过他更像是内建了 json* 函数（在之前可以 create_function 来干）

**Comment by ahxxm** [comment]
我硬盘比较小所以得压缩一点..

**Comment by shellexy** [comment]
好吧，
不过，单条推文的 json 就算用 xz 一般也只有不到一半的压缩率，

**Comment by ahxxm** [comment]
Status直接`json.dumps`失败，找了一下代码才发现有个`._json`可以用，…… 这样还挺省空间的，我试试psql再看怎么存

**Comment by ahxxm** [comment]
psql合理，磁盘再也不会爆炸了，见readme...

**Comment by shellexy** [comment]
赞 AI 酱
